name: DiscordRewards
main: eu.mcdb.discordrewards.bukkit.DiscordRewardsBukkit
author: Sheidy
version: ${project.version}
depend: [Spicord]
api-version: 1.13
commands:
  link:
    aliases: [discord]
  unlink:
    aliases: [unlink-discord]
