name: DiscordRewards
main: me.tini.discordrewards.bukkit.DiscordRewardsBukkit
author: Tini
version: ${project.version}
depend: [ Spicord ]
api-version: 1.13
commands:
  link:
    aliases: [ discord ]
  unlink:
    aliases: [ unlink-discord ]
